### ISSUE TITLE
Add support for multiple Modbus TCP connections

### ISSUE THREAD

**Issue by jeff47** [MarcusWichelmann/SolarEdgeExporter#2]
I have two inverters for my house, both have Modbus TCP enabled.  Do I need to collect from both -- and run two instances of SolarEdgeExporter, one for each?

**Comment by MarcusWichelmann** [comment]
Hi,

yes, it looks like, that each inverter only exports its own local metrics, they are not aggregated. Even in a master-slave setup.

But you're lucky, because I have the same issue right now and plan to implement support for multiple inverters in the very near future. So you won't have to run multiple instances of the exporter then.

So please be patient, I'm working on it. 👍🏼

**Comment by jeff47** [comment]
Awesome!

**Comment by jeff47** [comment]
https://www.packetmischief.ca/2022/01/09/monitoring-a-multi-inverter-solaredge-system/

There might be something here that could help too.

**Comment by MarcusWichelmann** [comment]
Nearly finished. Currently working on also adding InfluxDB support, then I'll release it as a new major version (because of breaking config changes).

**Comment by jeff47** [comment]
> Nearly finished. Currently working on also adding InfluxDB support, then I'll release it as a new major version (because of breaking config changes).

Any docs and tips you have on getting influxdb up and running would be great -- I've not used it yet, and finding it a little confusing!

**Comment by MarcusWichelmann** [comment]
I'm just using their docker image: https://hub.docker.com/_/influxdb
And here is a described, how you can generate the token that you can then give to the SolarEdgeExporter: https://www.influxdata.com/blog/getting-started-with-c-and-influxdb/

**Comment by MarcusWichelmann** [comment]
It's released: https://github.com/MarcusWichelmann/SolarEdgeExporter/releases/tag/v2.0.0
You'll have to update your `appsettings.json` because of some breaking changes. Please check the README for details.

Have fun and please let me know if everything works. ;)
